Repository 2025-sosuso/Capstone-Server, pull requests merged in 2025-06, with the labels that each got.

#50 [FEATURE] AI 분석 요청 미응답시 처리 로직 추가
  src/main/java/com/knu/sosuso/capstone/domain/Video.java
  src/main/java/com/knu/sosuso/capstone/dto/response/VideoApiResponse.java
  src/main/java/com/knu/sosuso/capstone/service/CommentService.java
  src/main/java/com/knu/sosuso/capstone/service/SearchService.java
  src/main/java/com/knu/sosuso/capstone/service/VideoService.java
Labels: 🐛 bug, 💫 feat, ♻️ refactor

#57 [FEATURE] Video 테이블에 필드 추가 및 저장 로직 개선
  src/main/java/com/knu/sosuso/capstone/domain/Video.java
  src/main/java/com/knu/sosuso/capstone/service/VideoProcessingService.java
  src/main/java/com/knu/sosuso/capstone/service/VideoService.java
Labels: 💫 feat

#66 [FEATURE] YouTube 영상 분석 시스템 구조 개선 및 새로운 응답 포맷 적용
  src/main/java/com/knu/sosuso/capstone/ai/dto/AIAnalysisRequest.java
  src/main/java/com/knu/sosuso/capstone/ai/dto/AIAnalysisResponse.java
  src/main/java/com/knu/sosuso/capstone/ai/service/AnalysisService.java
  src/main/java/com/knu/sosuso/capstone/controller/SearchController.java
  src/main/java/com/knu/sosuso/capstone/domain/Comment.java
  src/main/java/com/knu/sosuso/capstone/domain/Video.java
  src/main/java/com/knu/sosuso/capstone/dto/DefaultResponseData.java
  src/main/java/com/knu/sosuso/capstone/dto/ResponseData.java
  src/main/java/com/knu/sosuso/capstone/dto/ResponseDto.java
  src/main/java/com/knu/sosuso/capstone/dto/response/CommentApiResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/SearchChannelResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/SearchResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/SearchUrlResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/AnalysisResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/ChannelResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/CommentResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/SearchApiResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/SearchChannelResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/SearchResultResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/VideoResponse.java
  src/main/java/com/knu/sosuso/capstone/repository/CommentRepository.java
  src/main/java/com/knu/sosuso/capstone/repository/VideoRepository.java
  src/main/java/com/knu/sosuso/capstone/service/ChannelService.java
  src/main/java/com/knu/sosuso/capstone/service/CommentService.java
  src/main/java/com/knu/sosuso/capstone/service/ResponseMappingService.java
  src/main/java/com/knu/sosuso/capstone/service/SearchService.java
  src/main/java/com/knu/sosuso/capstone/service/TrendingService.java
  src/main/java/com/knu/sosuso/capstone/service/VideoProcessingService.java
  src/main/java/com/knu/sosuso/capstone/service/VideoService.java
Labels: 💫 feat

#69 [FEATURE] 좋아요 TOP 5 및 댓글 검색 기능 구현
  src/main/java/com/knu/sosuso/capstone/controller/VideoController.java
  src/main/java/com/knu/sosuso/capstone/dto/response/comment/CommentSearchDto.java
  src/main/java/com/knu/sosuso/capstone/dto/response/comment/CommentSearchResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/ChannelSearchResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/SearchApiResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/SearchResultResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/UrlAnalysisDto.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/UrlChannelDto.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/UrlCommentDto.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/UrlSearchResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/UrlVideoDto.java
  src/main/java/com/knu/sosuso/capstone/repository/CommentRepository.java
  src/main/java/com/knu/sosuso/capstone/service/ChannelService.java
  src/main/java/com/knu/sosuso/capstone/service/CommentQueryService.java
  src/main/java/com/knu/sosuso/capstone/service/ResponseMappingService.java
  src/main/java/com/knu/sosuso/capstone/service/SearchService.java
  src/main/java/com/knu/sosuso/capstone/service/TrendingService.java
  src/main/java/com/knu/sosuso/capstone/service/VideoProcessingService.java
Labels: 💫 feat

#74 [FEATURE] 구글 소셜 로그아웃 기능 구현
  src/main/java/com/knu/sosuso/capstone/controller/AuthController.java
  src/main/java/com/knu/sosuso/capstone/security/CustomSuccessHandler.java
  src/main/java/com/knu/sosuso/capstone/service/AuthService.java
  src/main/java/com/knu/sosuso/capstone/swagger/AuthControllerSwagger.java
Labels: 💫 feat

#75 [FEATURE] 스크랩 생성 기능 구현
  src/main/java/com/knu/sosuso/capstone/controller/ScrapController.java
  src/main/java/com/knu/sosuso/capstone/domain/Scrap.java
  src/main/java/com/knu/sosuso/capstone/dto/request/CreateScrapRequest.java
  src/main/java/com/knu/sosuso/capstone/dto/response/CreateScrapResponse.java
  src/main/java/com/knu/sosuso/capstone/repository/ScrapRepository.java
  src/main/java/com/knu/sosuso/capstone/service/ScrapService.java
Labels: 💫 feat

#77 [FEATURE] 스크랩 취소 기능 구현
  src/main/java/com/knu/sosuso/capstone/controller/ScrapController.java
  src/main/java/com/knu/sosuso/capstone/domain/Scrap.java
  src/main/java/com/knu/sosuso/capstone/service/ScrapService.java
  src/main/java/com/knu/sosuso/capstone/swagger/ScrapControllerSwagger.java
Labels: 💫 feat

#79 [FEATURE] 감정별 댓글 분류 기능 구현
  src/main/java/com/knu/sosuso/capstone/controller/SearchController.java
  src/main/java/com/knu/sosuso/capstone/controller/VideoController.java
  src/main/java/com/knu/sosuso/capstone/domain/value/SentimentType.java
  src/main/java/com/knu/sosuso/capstone/dto/response/comment/CommentDto.java
  src/main/java/com/knu/sosuso/capstone/dto/response/comment/CommentResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/comment/CommentSearchResponse.java
  src/main/java/com/knu/sosuso/capstone/repository/CommentRepository.java
  src/main/java/com/knu/sosuso/capstone/service/CommentQueryService.java
  src/main/java/com/knu/sosuso/capstone/service/SearchService.java
  src/main/java/com/knu/sosuso/capstone/service/VideoProcessingService.java
  src/main/java/com/knu/sosuso/capstone/service/VideoService.java
Labels: 💫 feat

#83 [FEATURE] 관심 채널 등록 취소 기능 구현
  src/main/java/com/knu/sosuso/capstone/controller/FavoriteChannelController.java
  src/main/java/com/knu/sosuso/capstone/dto/response/favorite_channel/CancelFavoriteChannelResponse.java
  src/main/java/com/knu/sosuso/capstone/service/FavoriteChannelService.java
  src/main/java/com/knu/sosuso/capstone/swagger/FavoriteChannelControllerSwagger.java
Labels: 💫 feat

#85 [FEATURE] Custom Exception 구현
  src/main/java/com/knu/sosuso/capstone/exception/BusinessException.java
  src/main/java/com/knu/sosuso/capstone/exception/ErrorResponse.java
  src/main/java/com/knu/sosuso/capstone/exception/ExceptionHandlerAdvice.java
  src/main/java/com/knu/sosuso/capstone/exception/error/AuthenticationError.java
  src/main/java/com/knu/sosuso/capstone/exception/error/BaseError.java
  src/main/java/com/knu/sosuso/capstone/exception/error/FavoriteChannelError.java
  src/main/java/com/knu/sosuso/capstone/exception/error/ScrapError.java
  src/main/java/com/knu/sosuso/capstone/exception/error/VideoError.java
  src/main/java/com/knu/sosuso/capstone/service/FavoriteChannelService.java
  src/main/java/com/knu/sosuso/capstone/service/ScrapService.java
Labels: 💫 feat

#86 [FEATURE] 키워드별 댓글 분류 기능 구현
  src/main/java/com/knu/sosuso/capstone/controller/CommentController.java
  src/main/java/com/knu/sosuso/capstone/controller/SearchController.java
  src/main/java/com/knu/sosuso/capstone/controller/TrendingController.java
  src/main/java/com/knu/sosuso/capstone/controller/VideoController.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/ChannelSearchResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/UrlChannelDto.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/UrlVideoDto.java
  src/main/java/com/knu/sosuso/capstone/repository/CommentRepository.java
  src/main/java/com/knu/sosuso/capstone/repository/FavoriteChannelRepository.java
  src/main/java/com/knu/sosuso/capstone/repository/ScrapRepository.java
  src/main/java/com/knu/sosuso/capstone/service/ChannelService.java
  src/main/java/com/knu/sosuso/capstone/service/CommentQueryService.java
  src/main/java/com/knu/sosuso/capstone/service/ResponseMappingService.java
  src/main/java/com/knu/sosuso/capstone/service/SearchService.java
  src/main/java/com/knu/sosuso/capstone/service/TrendingService.java
  src/main/java/com/knu/sosuso/capstone/service/UserDataService.java
  src/main/java/com/knu/sosuso/capstone/service/VideoProcessingService.java
Labels: 💫 feat

#91 [FEATURE] 응답 구조 수정 완료
  src/main/java/com/knu/sosuso/capstone/controller/TrendingController.java
  src/main/java/com/knu/sosuso/capstone/controller/VideoDetailController.java
  src/main/java/com/knu/sosuso/capstone/dto/response/VideoSummaryResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/detail/DetailAnalysisDto.java
  src/main/java/com/knu/sosuso/capstone/dto/response/detail/DetailChannelDto.java
  src/main/java/com/knu/sosuso/capstone/dto/response/detail/DetailCommentDto.java
  src/main/java/com/knu/sosuso/capstone/dto/response/detail/DetailPageResponse.java
  src/main/java/com/knu/sosuso/capstone/dto/response/detail/DetailVideoDto.java
  src/main/java/com/knu/sosuso/capstone/dto/response/search/UrlSearchResponse.java
  src/main/java/com/knu/sosuso/capstone/service/ResponseMappingService.java
  src/main/java/com/knu/sosuso/capstone/service/SearchService.java
  src/main/java/com/knu/sosuso/capstone/service/TrendingService.java
  src/main/java/com/knu/sosuso/capstone/service/VideoProcessingService.java
Labels: 💫 feat, ♻️ refactor

#92 feat: 사용자 스크랩 페이지 조회 #89
  src/main/java/com/knu/sosuso/capstone/ai/service/AnalysisService.java
  src/main/java/com/knu/sosuso/capstone/controller/ScrapController.java
  src/main/java/com/knu/sosuso/capstone/repository/ScrapRepository.java
  src/main/java/com/knu/sosuso/capstone/service/ScrapService.java
Labels: 💫 feat

#97 [FIX] 댓글 및 토큰이 없는 경우 적절한 처리 구현
  src/main/java/com/knu/sosuso/capstone/service/CommentService.java
  src/main/java/com/knu/sosuso/capstone/service/MainPageService.java
Labels: 🐛 bug
